#TODO Update for RHCL 1.2.0 once new builds exist

apiVersion: v1
data:
  "4.16": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-2-rhcl-console-plugin@sha256:cd1bed3b072ced00f455fcd7e96eec51023cfe906321bb5afe0a9bae94ba2c22
  "4.17": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-2-rhcl-console-plugin@sha256:cd1bed3b072ced00f455fcd7e96eec51023cfe906321bb5afe0a9bae94ba2c22
  "4.18": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-2-rhcl-console-plugin@sha256:cd1bed3b072ced00f455fcd7e96eec51023cfe906321bb5afe0a9bae94ba2c22
  "4.19": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-2-rhcl-console-plugin@sha256:cd1bed3b072ced00f455fcd7e96eec51023cfe906321bb5afe0a9bae94ba2c22
  "4.20": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-2-rhcl-console-plugin@sha256:cd1bed3b072ced00f455fcd7e96eec51023cfe906321bb5afe0a9bae94ba2c22
  default: quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-2-rhcl-console-plugin@sha256:cd1bed3b072ced00f455fcd7e96eec51023cfe906321bb5afe0a9bae94ba2c22
kind: ConfigMap
metadata:
  labels:
    app: kuadrant
    kuadrant-operator-console-plugin-images: "true"
  name: kuadrant-operator-console-plugin-images