apiVersion: v1
data:
  "4.16": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-1-rhcl-console-plugin@sha256:0b3d41e21b75aecb9a387d1e6fe29eb90973790fe980fd8b28f2d5df09b2cea9
  "4.17": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-1-rhcl-console-plugin@sha256:0b3d41e21b75aecb9a387d1e6fe29eb90973790fe980fd8b28f2d5df09b2cea9
  "4.18": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-1-rhcl-console-plugin@sha256:0b3d41e21b75aecb9a387d1e6fe29eb90973790fe980fd8b28f2d5df09b2cea9
  "4.19": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-1-rhcl-console-plugin@sha256:0b3d41e21b75aecb9a387d1e6fe29eb90973790fe980fd8b28f2d5df09b2cea9
  "4.20": quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-1-rhcl-console-plugin@sha256:0b3d41e21b75aecb9a387d1e6fe29eb90973790fe980fd8b28f2d5df09b2cea9
  default: quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-1-rhcl-console-plugin@sha256:0b3d41e21b75aecb9a387d1e6fe29eb90973790fe980fd8b28f2d5df09b2cea9
kind: ConfigMap
metadata:
  labels:
    app: kuadrant
    kuadrant-operator-console-plugin-images: "true"
  name: kuadrant-operator-console-plugin-images