name: Generate Bundle

on:
  push:
    paths:
      - 'image-pullspecs.yaml'
      - 'bundle-generation/**'
      - 'kuadrant-operator'
    branches:
      - 'rhcl-*'
  workflow_dispatch: # Allow manual triggering

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

jobs:
  generate-bundle:
    runs-on: ubuntu-latest
    container:
      image: quay.io/konflux-ci/yq:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate bundle and verify that changes exist
        run: |
          make verify-bundle

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
          commit_message: Generate Bundles after change to image-pullspecs.yaml or rhcl-operator.yaml
